


<section class=" text-center text-lg-start">
  <style>
    .rounded-t-5 {
      border-top-left-radius: 0.5rem;
      border-top-right-radius: 0.5rem;
    }

    @media (min-width: 992px) {
      .rounded-tr-lg-0 {
        border-top-right-radius: 0;
      }

      .rounded-bl-lg-5 {
        border-bottom-left-radius: 0.5rem;
      }
    }
  </style>
  <div class="card">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-6 d-none d-lg-flex">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSIzQlkEHFxRqkO6jG-2IyrwATyETZlzMUng&usqp=CAU"  width="60%" height="300" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5 m-5"/>
      </div>
      <div class="col-lg-6">
        <div class="card-body py-3 px-md-5">

        <?php echo $this->tag->form("login/login"); ?>
        <h1><b>Log in</b></h1>
            <!-- Email input -->
            <div class="form-outline mb-5">
              <input type="email" id="form2Example1" name="email" class="form-control" />
              <label class="form-label" for="form2Example1">Email address</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-5">
              <input type="password" id="form2Example2" name="password" class="form-control" />
              <label class="form-label" for="form2Example2">Password</label>
            </div>

            <!-- 2 column grid layout for inline styling -->
            <div class="row mb-4">
              <div class="col d-flex justify-content-center">
                <!-- Checkbox -->
                <div class="form-check">
                <?php echo $this->tag->checkField("remember-me"); ?>
                  <label class="form-check-label" for="form2Example31"> Remember me </label>
                </div>
              </div>

              <div class="col">
                <!-- Simple link -->
                <a href="#!">Forgot password?</a>
              </div>
            </div>

            <!-- Submit button -->
            <button type="submit" name="login" class="btn btn-primary btn-block mb-4">Sign in</button>

          </form>

        </div>
      </div>
    </div>
  </div>
</section>