<?php
echo '<div>';

    echo '<h1>Tracks</h1>';

    echo '<div class="container px-4 px-lg-5 mt-5" id="main">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 ">';
    foreach ($tracks as $k => $v) {
        echo '<div class="col mb-5" >
    <div class="card" style="width: 15rem;">
    <img class="card-img-top" src="' . $v['track']['album']['images'][0]['url'] . '" alt="no image" width="70%" height="70%">
    <div class="card-body">
    <h5 class="card-title">' . $v['track']['name'] . '</h5>
    <p class="card-text">by: ' . $v['track']['album']['artists'][0]['name'] . ' </p>
    <form action="removeFromPlaylist" method="POST">
    <button type="submit" value="'.$v['track']['uri'].'" name="removeFromPlaylist" >Remove From Playlist </button>
    </form>
   </div>
  </div>
</div>
';
    }

echo '</div>
</div>';
